<?php declare(strict_types = 1);

use Tracy\Dumper;

/** @var array<array<mixed>> $records */

?>
<h1>Log records</h1>

<div class="tracy-inner">
	<table class="tracy-sortable">
		<tr>
			<th>Level</th>
			<th>Channel</th>
			<th>Time</th>
			<th>Message</th>
		</tr>
		<?php foreach ($records as $record): ?>
			<tr>
				<td><?= "{$record['level']} ({$record['level_name']})" ?></td>
				<td><?= $record['channel'] ?></td>
				<td><?= $record['datetime']->format('H:i:s.u'); ?></td>
				<td>
					<?php
					echo $record['message'];
					echo Dumper::toHtml($record['context'], [Dumper::LIVE => true]);
					echo Dumper::toHtml($record['extra'], [Dumper::LIVE => true, Dumper::COLLAPSE => true]);
					?>
				</td>
			</tr>
		<?php endforeach; ?>
	</table>
</div>
